/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION dz60
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef LED_CAPS_LOCK_PIN
#   define LED_CAPS_LOCK_PIN B2
#endif // LED_CAPS_LOCK_PIN

#ifndef MANUFACTURER
#   define MANUFACTURER KBDFans
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN E2
#endif // RGB_DI_PIN

#ifndef PRODUCT
#   define PRODUCT dz60
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x2260
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x445A
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 15
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { F0, F1, E6, C7, C6, B7, D4, B1, B0, B5, B4, D7, D6, B3, F4 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 5
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { D0, D1, D2, D3, D5 }
#endif // MATRIX_ROW_PINS
